services:
  app:
    image: app_airport
    container_name: app_airport
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "80:3000"  
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  microservice-flights:
    image: microservice-flights:v1
    container_name: microservice-flights
    build:
      context: ./flights
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672"
    networks:
      - ms_nestjs

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017" 
    networks:
      - ms_nestjs

volumes:
  mongodb:

networks:
  ms_nestjs:
    driver: bridge
